apiVersion: v1
kind: PersistentVolume
metadata:
  name: fintech-pv
spec:
  storageClassName: fintech-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/fintech-db
