apiVersion: v1
kind: Namespace
metadata:
  name: fintech
  labels:
    app.kubernetes.io/name: fintech
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
