apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fintech-db
  namespace: fintech
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: fintech-db
      role: db
  template:
    metadata:
      labels:
        app: fintech-db
        role: db
    spec:
      containers:
        - name: postgres
          image: apauldev/postgres-fintech:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fintech-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fintech-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
