apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: fintech
  labels:
    app: fintech-db
    role: db
spec:
  type: ClusterIP
  selector:
    app: fintech-db
    role: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
