apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-config
  namespace: fintech
data:
  FRONTEND_HOST: http://fintech.local
  BACKEND_URL: http://backend-service:9091
  DB_HOST: db-service
  DB_NAME: devsudb
  DB_PORT: "5432"
