apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: fintech
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: fintech
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: fintech
automountServiceAccountToken: false
